### ISSUE TITLE
Build Test: Windows MinGW/Cygwin

### ISSUE THREAD

**Issue by zpl-zak** [zaklaus/DZMLang#31]

**Comment by zpl-zak** [comment]
Build process fails on MinGW due to missing pthread.h. I need to investigate this issue further.

**Comment by zaklaus** [comment]
Windows build requires wrapped pthread calls, possibly using macro to separate Linux/Win code, where Windows should refer to WINAPI solution. CMake should generate working VS project. MinGW is questionable now.

**Comment by gamelaster** [comment]
pthread.h is just Unix(POSIX) only, needs to use Win32 Threads, only CYGWIN could build probably, but not sure.
